ENV = "E:/SmartSecurity/SmartSecurityWeb/lib/x64/debug/opencv_world4120.dll"
#ENV = "/mnt/e/SmartSecurity/testRun/lib/x64/debug/libopencv_world.so.412"
LibPath = "lib/x64/debug/SmartSecurityCoreLibTest"
#LibPath = "/mnt/e/SmartSecurity/testRun/lib/x64/debug/libSmartSecurityCoreLibTest"
YOLOV5ConfigPath = "./lib/x64/debug/config/yoloConfig.json"
SSDConfigPath = "./lib/x64/debug/config/coffeConfig.json"
FaceNetPath = "./lib/x64/debug/config/facenet.json"
SRPath = "./lib/x64/debug/config/sr.json"
YuNetPath="./lib/x64/debug/config/yunet.json"
ArcFacePath="lib/x64/debug/config/arcface.json"
YOLOBootPath = "./lib/x64/debug/config/yoloBoot.json"
