import org.springframework.boot.gradle.plugin.SpringBootPlugin

plugins {
    id 'java'
    id 'org.springframework.boot' version '3.5.3'  // 新增Spring Boot插件
    id 'io.spring.dependency-management' version '1.1.4'  // 新增依赖管理插件
}

group = 'com.erling'
version = '1.0-SNAPSHOT'
ext {
    springAiVersion = "1.0.0-RC1"
}
repositories {
    mavenCentral()
    maven { url 'https://repo.spring.io/snapshot' }
}

subprojects {
    apply plugin: 'java'
    apply plugin: 'io.spring.dependency-management'
    apply plugin: 'org.springframework.boot' // 子模块单独应用Spring Boot插件

    dependencyManagement {
        imports {
            mavenBom SpringBootPlugin.BOM_COORDINATES
            mavenBom "org.springframework.ai:spring-ai-bom:$springAiVersion"
        }
    }

    // 公共测试依赖
    dependencies {

        testImplementation 'org.springframework.boot:spring-boot-starter-test' // 测试依赖
    }
    dependencies {
        implementation 'org.projectlombok:lombok'
        annotationProcessor 'org.projectlombok:lombok' // 添加注解处理器
        implementation 'org.springframework.boot:spring-boot-starter-actuator' // 监控和管理
        implementation 'org.springframework.boot:spring-boot-starter-web' //Spring Web
        implementation 'org.springframework.boot:spring-boot-starter-websocket'

        implementation 'org.springframework.boot:spring-boot-starter-aop' // 面向切面编程

        implementation 'org.mybatis.spring.boot:mybatis-spring-boot-starter:3.0.3'
        implementation 'org.springframework.boot:spring-boot-starter-security'

        implementation 'org.springframework.boot:spring-boot-starter-validation'

        // 新增 MyBatis Plus 依赖
        implementation 'com.baomidou:mybatis-plus-boot-starter:3.5.5'
        annotationProcessor 'com.baomidou:mybatis-plus-generator:3.5.5'
        implementation 'mysql:mysql-connector-java:8.0.33'

        // 新增 Redis 依赖
//        implementation "org.springframework.boot:spring-boot-starter-redis:1.3.5.RELEASE"

        implementation 'org.springframework.boot:spring-boot-starter-data-redis'

        implementation 'io.jsonwebtoken:jjwt-api:0.11.5'
        implementation 'io.jsonwebtoken:jjwt-impl:0.11.5'
        implementation 'io.jsonwebtoken:jjwt-jackson:0.11.5'

        implementation 'com.github.penggle:kaptcha:2.3.2' // 验证码

        implementation 'org.springframework.integration:spring-integration-mqtt'
        implementation 'org.eclipse.paho:org.eclipse.paho.client.mqttv3:1.2.5'

        implementation 'org.springframework.ai:spring-ai-openai'
//        implementation 'org.springframework.ai:spring-ai-openai-spring-boot-starter'
        implementation 'org.springframework.ai:spring-ai-starter-model-openai'
    }
    dependencies {
        implementation 'net.java.dev.jna:jna:5.14.0'
    }


    test {
        useJUnitPlatform()
    }
}
bootJar {
    mainClass = 'com.erling.Application' // 替换为你的主类全限定名
}
test {
    useJUnitPlatform()
}