plugins {
    id 'java'
}

group = 'com.erling'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation project(':Controller') // 添加模块依赖
    implementation project(':Utils') // 添加模块依赖
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'

}

test {
    useJUnitPlatform()
    workingDir= file('E:\\SmartSecurity\\SmartSecurityWeb')
}