
plugins {
    id 'java'
}

group = 'com.erling'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation project(":Dao")
    implementation project(":Pojo")
    implementation project(":Opencv_Dlib")
    implementation project(":Utils")
//    implementation project(':Main') // 添加模块依赖
//    implementation 'org.springframework.ai:spring-ai-starter-model-openai'
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
}
bootJar {
    enabled = false
}
jar {
    enabled = true
}
test {
    useJUnitPlatform()
}