plugins {
    id 'java'
}

group = 'com.erling'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {


    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    implementation project(":Utils")
}
bootJar {
//    enabled = false
    mainClass = 'com.erling.Application' // 替换为你的主类全限定名
}


jar {
    enabled = true
}
test {
    useJUnitPlatform()
}