tcp:
  service:
     port: 12346
  connection:
     threads: 24
     timeout: 30000
spring:
  mqtt:
    broker: tcp://localhost:1883
    client-id: mqtt-client
    username: admin
    password: 123456
    default-topic: /topic/#
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  logging:
    level:
      root: DEBUG
  ai:
    openai:
      base-url: https://api.deepseek.com
      api-key:
      chat:
        options:
          model: deepseek-chat


  datasource:
    url: jdbc:mysql://localhost:3306/smartsecuritydb
    username: root
    password: 123456
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss  # 新增日期格式配置
    time-zone: GMT+8                  # 设置时区
    serialization:
      write-dates-as-timestamps:
  flyway:
    loggers: slf4j
#  data:
#    redis:
#      host: localhost
#      port: 6379
#      timeout: 10000
#      database: 1


Idebug:
  showDebug: true
  islog: true



mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 修正值为StdOutImpl
server:
  servlet:
    encoding:
      force: true
      enabled: true
      charset: UTF-8
